// Auto-generated by zen-mock-data script
module.exports = {
  path: 'api/v1/people/match',
  method: 'POST',
  generate: (faker, requestBody) => {
    return {
  "person": {
    "id": faker.string.uuid(),
    "first_name": faker.person.firstName(),
    "last_name": faker.person.lastName(),
    "name": faker.person.fullName(),
    "linkedin_url": "http://www.linkedin.com/in/tim-zheng-677ba010",
    "title": faker.person.jobTitle(),
    "email_status": "verified",
    "photo_url": "https://static.licdn.com/aero-v1/sc/h/9c8pery4andzj6ohjkjp54ma2",
    "twitter_url": null,
    "github_url": null,
    "facebook_url": null,
    "extrapolated_email_confidence": null,
    "headline": "Founder & CEO at Apollo",
    "email": faker.internet.email(),
    "organization_id": "5e66b6381e05b4008c8331b8",
    "employment_history": [
      {
        "_id": "66d7af8c200cad0001404c1f",
        "created_at": null,
        "current": true,
        "degree": null,
        "description": null,
        "emails": null,
        "end_date": null,
        "grade_level": null,
        "kind": null,
        "major": null,
        "organization_id": "5e66b6381e05b4008c8331b8",
        "organization_name": faker.company.name(),
        "raw_address": null,
        "start_date": "2016-01-01",
        "title": faker.person.jobTitle(),
        "updated_at": null,
        "id": faker.string.uuid(),
        "key": "66d7af8c200cad0001404c1f"
      },
      {
        "_id": "66d7af8c200cad0001404c20",
        "created_at": null,
        "current": false,
        "degree": null,
        "description": null,
        "emails": null,
        "end_date": "2015-01-01",
        "grade_level": null,
        "kind": null,
        "major": null,
        "organization_id": null,
        "organization_name": faker.company.name(),
        "raw_address": null,
        "start_date": "2011-01-01",
        "title": faker.person.jobTitle(),
        "updated_at": null,
        "id": faker.string.uuid(),
        "key": "66d7af8c200cad0001404c20"
      },
      {
        "_id": "66d7af8c200cad0001404c21",
        "created_at": null,
        "current": false,
        "degree": null,
        "description": null,
        "emails": null,
        "end_date": "2011-01-01",
        "grade_level": null,
        "kind": null,
        "major": null,
        "organization_id": "54a22f23746869331840e813",
        "organization_name": faker.company.name(),
        "raw_address": null,
        "start_date": "2011-01-01",
        "title": faker.person.jobTitle(),
        "updated_at": null,
        "id": faker.string.uuid(),
        "key": "66d7af8c200cad0001404c21"
      },
      {
        "_id": "66d7af8c200cad0001404c22",
        "created_at": null,
        "current": false,
        "degree": null,
        "description": null,
        "emails": null,
        "end_date": "2010-09-01",
        "grade_level": null,
        "kind": null,
        "major": null,
        "organization_id": "54a1216169702d7fe6dfca02",
        "organization_name": faker.company.name(),
        "raw_address": null,
        "start_date": "2010-08-01",
        "title": faker.person.jobTitle(),
        "updated_at": null,
        "id": faker.string.uuid(),
        "key": "66d7af8c200cad0001404c22"
      },
      {
        "_id": "66d7af8c200cad0001404c23",
        "created_at": null,
        "current": false,
        "degree": null,
        "description": null,
        "emails": null,
        "end_date": "2010-08-01",
        "grade_level": null,
        "kind": null,
        "major": null,
        "organization_id": "5da2e6a3f978a8000177e831",
        "organization_name": faker.company.name(),
        "raw_address": null,
        "start_date": "2010-06-01",
        "title": faker.person.jobTitle(),
        "updated_at": null,
        "id": faker.string.uuid(),
        "key": "66d7af8c200cad0001404c23"
      },
      {
        "_id": "66d7af8c200cad0001404c24",
        "created_at": null,
        "current": false,
        "degree": null,
        "description": null,
        "emails": null,
        "end_date": "2010-02-01",
        "grade_level": null,
        "kind": null,
        "major": null,
        "organization_id": "54a1a06274686945fa1ffc02",
        "organization_name": faker.company.name(),
        "raw_address": null,
        "start_date": "2009-12-01",
        "title": faker.person.jobTitle(),
        "updated_at": null,
        "id": faker.string.uuid(),
        "key": "66d7af8c200cad0001404c24"
      }
    ],
    "state": faker.location.state(),
    "city": faker.location.city(),
    "country": faker.location.country(),
    "contact_id": "664fa05cf8299f0001f90876",
    "contact": {
      "contact_roles": [],
      "id": faker.string.uuid(),
      "first_name": faker.person.firstName(),
      "last_name": faker.person.lastName(),
      "name": faker.person.fullName(),
      "linkedin_url": "http://www.linkedin.com/in/tim-zheng-677ba010",
      "title": faker.person.jobTitle(),
      "contact_stage_id": "6095a710bd01d100a506d4ae",
      "owner_id": null,
      "creator_id": "66302798d03b9601c7934ec2",
      "person_id": "64a7ff0cc4dfae00013df1a5",
      "email_needs_tickling": null,
      "organization_name": faker.company.name(),
      "source": "crm",
      "original_source": "crm",
      "organization_id": "5e66b6381e05b4008c8331b8",
      "headline": "Reaching Peak Potential 💪⛰️📈🧪️ | President at FRC",
      "photo_url": null,
      "present_raw_address": "New York, New York, United States",
      "linkedin_uid": null,
      "extrapolated_email_confidence": null,
      "salesforce_id": null,
      "salesforce_lead_id": null,
      "salesforce_contact_id": null,
      "salesforce_account_id": null,
      "crm_owner_id": null,
      "created_at": faker.date.past(),
      "emailer_campaign_ids": [],
      "direct_dial_status": null,
      "direct_dial_enrichment_failed_at": null,
      "email_status": "verified",
      "email_source": null,
      "account_id": "6658955877a2f20001c648ac",
      "last_activity_date": null,
      "hubspot_vid": null,
      "hubspot_company_id": null,
      "crm_id": null,
      "sanitized_phone": "+11234567890",
      "merged_crm_ids": null,
      "updated_at": faker.date.recent(),
      "queued_for_crm_push": null,
      "suggested_from_rule_engine_config_id": null,
      "email_unsubscribed": null,
      "label_ids": [],
      "has_pending_email_arcgate_request": false,
      "has_email_arcgate_request": false,
      "existence_level": "invisible",
      "email": faker.internet.email(),
      "email_from_customer": true,
      "typed_custom_fields": {},
      "custom_field_errors": null,
      "crm_record_url": null,
      "email_status_unavailable_reason": null,
      "email_true_status": "Verified",
      "updated_email_true_status": false,
      "contact_rule_config_statuses": [],
      "source_display_name": "Imported from CRM",
      "contact_emails": [
        {
          "email": faker.internet.email(),
          "email_md5": "879440a4afe6515e2de11dd7c531b770",
          "email_sha256": "354f0caf2a603f6bd8e1646693ad829615254584fd83692766ac2db3aaa58e0f",
          "email_status": "verified",
          "email_source": null,
          "extrapolated_email_confidence": null,
          "position": 0,
          "email_from_customer": null,
          "free_domain": false
        }
      ],
      "time_zone": "America/Los_Angeles",
      "phone_numbers": [
        {
          "raw_number": "(123) 456-7890",
          "sanitized_number": "+11234567890",
          "type": null,
          "position": 0,
          "status": "valid_number",
          "dnc_status": null,
          "dnc_other_info": null,
          "dialer_flags": null
        },
        {
          "raw_number": "(123) 456-1234",
          "sanitized_number": "+11234561234",
          "type": null,
          "position": 1,
          "status": "valid_number",
          "dnc_status": null,
          "dnc_other_info": null,
          "dialer_flags": null
        },
        {
          "raw_number": "+1-415-763-6055",
          "sanitized_number": "+14157636055",
          "type": null,
          "position": 2,
          "status": "valid_number",
          "dnc_status": null,
          "dnc_other_info": null,
          "dialer_flags": {
            "country_name": "United States",
            "country_enabled": true,
            "high_risk_calling_enabled": false,
            "potential_high_risk_number": false
          }
        }
      ],
      "account_phone_note": null,
      "free_domain": false,
      "is_likely_to_engage": false
    },
    "revealed_for_current_team": true,
    "organization": {
      "id": faker.string.uuid(),
      "name": faker.person.fullName(),
      "website_url": "http://www.apollo.io",
      "blog_url": null,
      "angellist_url": null,
      "linkedin_url": "http://www.linkedin.com/company/apolloio",
      "twitter_url": "https://twitter.com/meetapollo/",
      "facebook_url": "https://www.facebook.com/MeetApollo",
      "primary_phone": {},
      "languages": [],
      "alexa_ranking": 3514,
      "phone": null,
      "linkedin_uid": "18511550",
      "founded_year": 2015,
      "publicly_traded_symbol": null,
      "publicly_traded_exchange": null,
      "logo_url": "https://zenprospect-production.s3.amazonaws.com/uploads/pictures/66d13c8d98ec9600013525b8/picture",
      "crunchbase_url": null,
      "primary_domain": "apollo.io",
      "industry": "information technology & services",
      "keywords": [
        "sales engagement",
        "lead generation",
        "predictive analytics",
        "lead scoring",
        "sales strategy",
        "conversation intelligence",
        "sales enablement",
        "lead routing",
        "sales development",
        "email engagement",
        "revenue intelligence",
        "sales operations",
        "sales intelligence",
        "lead intelligence",
        "prospecting",
        "b2b data"
      ],
      "estimated_num_employees": 1600,
      "industries": [
        "information technology & services"
      ],
      "secondary_industries": [],
      "snippets_loaded": true,
      "industry_tag_id": "5567cd4773696439b10b0000",
      "industry_tag_hash": {
        "information technology & services": "5567cd4773696439b10b0000"
      },
      "retail_location_count": 0,
      "raw_address": "415 Mission St, Floor 37, San Francisco, California 94105, US",
      "street_address": "415 Mission St",
      "city": faker.location.city(),
      "state": faker.location.state(),
      "postal_code": "94105-2301",
      "country": faker.location.country(),
      "owned_by_organization_id": null,
      "seo_description": "Search, engage, and convert over 275 million contacts at over 73 million companies with Apollo's sales intelligence and engagement platform.",
      "short_description": "Apollo.io combines a buyer database of over 270M contacts and powerful sales engagement and automation tools in one, easy to use platform. Trusted by over 160,000 companies including Autodesk, Rippling, Deel, Jasper.ai, Divvy, and Heap, Apollo has more than one million users globally. By helping sales professionals find their ideal buyers and intelligently automate outreach, Apollo helps go-to-market teams sell anything.\n\nCelebrating a $100M Series D Funding Round 🦄",
      "suborganizations": [],
      "num_suborganizations": 0,
      "annual_revenue_printed": "100M",
      "annual_revenue": 100000000,
      "total_funding": 251200000,
      "total_funding_printed": "251.2M",
      "latest_funding_round_date": "2023-08-01T00:00:00.000+00:00",
      "latest_funding_stage": "Series D",
      "funding_events": [
        {
          "id": faker.string.uuid(),
          "date": "2023-08-01T00:00:00.000+00:00",
          "news_url": null,
          "type": "Series D",
          "investors": "Bain Capital Ventures, Sequoia Capital, Tribe Capital, Nexus Venture Partners",
          "amount": "100M",
          "currency": "$"
        },
        {
          "id": faker.string.uuid(),
          "date": "2022-03-01T00:00:00.000+00:00",
          "news_url": null,
          "type": "Series C",
          "investors": "Sequoia Capital, Tribe Capital, Nexus Venture Partners, NewView Capital",
          "amount": "110M",
          "currency": "$"
        },
        {
          "id": faker.string.uuid(),
          "date": "2021-10-01T00:00:00.000+00:00",
          "news_url": null,
          "type": "Series B",
          "investors": "Tribe Capital, NewView Capital, Nexus Venture Partners",
          "amount": "32M",
          "currency": "$"
        },
        {
          "id": faker.string.uuid(),
          "date": "2018-06-26T00:00:00.000+00:00",
          "news_url": "https://techcrunch.com/2018/06/26/yc-grad-zenprospect-rebrands-as-apollo-lands-7-m-series-a/",
          "type": "Series A",
          "investors": "Nexus Venture Partners, Social Capital, Y Combinator",
          "amount": "7M",
          "currency": "$"
        },
        {
          "id": faker.string.uuid(),
          "date": "2016-10-01T00:00:00.000+00:00",
          "news_url": null,
          "type": "Other",
          "investors": "Y Combinator, SV Angel, Social Capital, Nexus Venture Partners",
          "amount": "2.2M",
          "currency": "$"
        }
      ],
      "technology_names": [
        "AI",
        "Android",
        "Basis",
        "Canva",
        "Circle",
        "CloudFlare Hosting",
        "Cloudflare DNS",
        "Drift",
        "Gmail",
        "Google Apps",
        "Google Tag Manager",
        "Google Workspace",
        "Gravity Forms",
        "Hubspot",
        "Intercom",
        "Mailchimp Mandrill",
        "Marketo",
        "Microsoft Office 365",
        "Mobile Friendly",
        "Python",
        "Rackspace MailGun",
        "Remote",
        "Render",
        "Reviews",
        "Salesforce",
        "Stripe",
        "Typekit",
        "WP Engine",
        "Wistia",
        "WordPress.org",
        "Yandex Metrica",
        "reCAPTCHA"
      ],
      "current_technologies": [
        {
          "uid": "ai",
          "name": faker.person.fullName(),
          "category": "Other"
        },
        {
          "uid": "android",
          "name": faker.person.fullName(),
          "category": "Frameworks and Programming Languages"
        },
        {
          "uid": "basis",
          "name": faker.person.fullName(),
          "category": "Advertising Networks"
        },
        {
          "uid": "canva",
          "name": faker.person.fullName(),
          "category": "Content Management Platform"
        },
        {
          "uid": "circle",
          "name": faker.person.fullName(),
          "category": "Financial Software"
        },
        {
          "uid": "cloudflare_hosting",
          "name": faker.person.fullName(),
          "category": "Hosting"
        },
        {
          "uid": "cloudflare_dns",
          "name": faker.person.fullName(),
          "category": "Domain Name Services"
        },
        {
          "uid": "drift",
          "name": faker.person.fullName(),
          "category": "Widgets"
        },
        {
          "uid": "gmail",
          "name": faker.person.fullName(),
          "category": "Email Providers"
        },
        {
          "uid": "google_apps",
          "name": faker.person.fullName(),
          "category": "Other"
        },
        {
          "uid": "google_tag_manager",
          "name": faker.person.fullName(),
          "category": "Tag Management"
        },
        {
          "uid": "google workspace",
          "name": faker.person.fullName(),
          "category": "Cloud Services"
        },
        {
          "uid": "gravity_forms",
          "name": faker.person.fullName(),
          "category": "Hosted Forms"
        },
        {
          "uid": "hubspot",
          "name": faker.person.fullName(),
          "category": "Marketing Automation"
        },
        {
          "uid": "intercom",
          "name": faker.person.fullName(),
          "category": "Support and Feedback"
        },
        {
          "uid": "mailchimp_mandrill",
          "name": faker.person.fullName(),
          "category": "Email Delivery"
        },
        {
          "uid": "marketo",
          "name": faker.person.fullName(),
          "category": "Marketing Automation"
        },
        {
          "uid": "office_365",
          "name": faker.person.fullName(),
          "category": "Other"
        },
        {
          "uid": "mobile_friendly",
          "name": faker.person.fullName(),
          "category": "Other"
        },
        {
          "uid": "python",
          "name": faker.person.fullName(),
          "category": "Frameworks and Programming Languages"
        },
        {
          "uid": "rackspace_mailgun",
          "name": faker.person.fullName(),
          "category": "Email Delivery"
        },
        {
          "uid": "remote",
          "name": faker.person.fullName(),
          "category": "Other"
        },
        {
          "uid": "render",
          "name": faker.person.fullName(),
          "category": "Other"
        },
        {
          "uid": "reviews",
          "name": faker.person.fullName(),
          "category": "Customer Reviews"
        },
        {
          "uid": "salesforce",
          "name": faker.person.fullName(),
          "category": "Customer Relationship Management"
        },
        {
          "uid": "stripe",
          "name": faker.person.fullName(),
          "category": "Payments"
        },
        {
          "uid": "typekit",
          "name": faker.person.fullName(),
          "category": "Fonts"
        },
        {
          "uid": "wp_engine",
          "name": faker.person.fullName(),
          "category": "CMS"
        },
        {
          "uid": "wistia",
          "name": faker.person.fullName(),
          "category": "Online Video Platforms"
        },
        {
          "uid": "wordpress_org",
          "name": faker.person.fullName(),
          "category": "CMS"
        },
        {
          "uid": "yandex_metrika",
          "name": faker.person.fullName(),
          "category": "Analytics and Tracking"
        },
        {
          "uid": "recaptcha",
          "name": faker.person.fullName(),
          "category": "Captcha"
        }
      ],
      "org_chart_root_people_ids": [
        "652fc57e2802bf00010c52f8"
      ],
      "org_chart_sector": "OrgChart::SectorHierarchy::Rules::IT",
      "org_chart_removed": false,
      "org_chart_show_department_filter": true
    },
    "is_likely_to_engage": true,
    "intent_strength": null,
    "show_intent": false,
    "departments": [
      "c_suite"
    ],
    "subdepartments": [
      "executive",
      "founder"
    ],
    "functions": [
      "entrepreneurship"
    ],
    "seniority": "founder"
  },
  "waterfall": {
    "status": "accepted",
    "message": "Waterfall enrichment request accepted. Results will be sent to the provided webhook URL."
  }
};
  }
};
