// Auto-generated by zen-mock-data script
module.exports = {
  path: '/v1/mixed_people/search',
  method: 'POST',
  generate: (faker, requestBody) => {
    return {
  "contacts": [
    {
      "first_name": faker.person.firstName(),
      "last_name": faker.person.lastName(),
      "email": faker.internet.email(),
      "organization_name": faker.company.name(),
      "title": faker.person.jobTitle(),
      "city": faker.location.city(),
      "custom_identifier": faker.string.uuid()
    }
  ],
  "pagination": {
    "total_pages": 1
  }
};
  }
};
