// Auto-generated by zen-mock-data script
module.exports = {
  path: 'search',
  method: 'POST',
  generate: (faker, requestBody) => {
    return {
      "searchParameters": {
        "q": "apple inc",
        "type": "search",
        "engine": "google"
      },
      "knowledgeGraph": {
        "title": faker.person.jobTitle(),
        "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5ITHsQzdzkkFWKinRe1Y4FUbC_Vy3R_M&s=0",
        "description": "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, in Silicon Valley, best known for its consumer electronics, software and online services.",
        "descriptionSource": "Wikipedia",
        "descriptionLink": "https://en.wikipedia.org/wiki/Apple_Inc.",
        "attributes": {
          "Customer service": faker.phone.number(),
          "Founders": "Steve Jobs, Steve Wozniak, and Ronald Wayne",
          "Founded": "April 1, 1976, Los Altos, CA",
          "Headquarters": "Cupertino, CA",
          "COO": "Sabih Khan",
          "CEO": "Tim Cook (Aug 24, 2011–)"
        }
      },
      "organic": [
        {
          "title": faker.person.jobTitle(),
          "link": "https://www.apple.com/",
          "snippet": "Discover the innovative world of Apple and shop everything iPhone, iPad, Apple Watch, Mac, and Apple TV, plus explore accessories, entertainment, ...",
          "sitelinks": [
            {
              "title": faker.person.jobTitle(),
              "link": "https://www.apple.com/careers/us/"
            },
            {
              "title": faker.person.jobTitle(),
              "link": "https://www.apple.com/leadership/"
            },
            {
              "title": faker.person.jobTitle(),
              "link": "https://www.apple.com/business/"
            },
            {
              "title": faker.person.jobTitle(),
              "link": "https://www.apple.com/store"
            },
            {
              "title": faker.person.jobTitle(),
              "link": "https://www.apple.com/newsroom/"
            }
          ],
          "position": 1
        },
        {
          "title": faker.person.jobTitle(),
          "link": "https://en.wikipedia.org/wiki/Apple_Inc.",
          "snippet": "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, in Silicon Valley, best known for its consumer electronics, ...",
          "position": 2
        },
        {
          "title": faker.person.jobTitle(),
          "link": "https://finance.yahoo.com/quote/AAPL/",
          "snippet": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.",
          "position": 3
        },
        {
          "title": faker.person.jobTitle(),
          "link": "https://www.britannica.com/money/Apple-Inc",
          "snippet": "Apple Inc. is an American multinational technology company that revolutionized the technology sector through its innovation of computer software, personal ...",
          "date": "8 days ago",
          "position": 4
        },
        {
          "title": faker.person.jobTitle(),
          "link": "https://www.linkedin.com/company/apple",
          "snippet": "Company size: 10,001+ employees. Headquarters: Cupertino, California. Type: Public Company. Founded: 1976. Specialties: Innovative Product ...",
          "date": "Jun 5, 2025",
          "position": 5
        },
        {
          "title": faker.person.jobTitle(),
          "link": "https://www.bloomberg.com/profile/company/AAPL:US",
          "snippet": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables and accessories, and sells a variety of related ...",
          "position": 6
        },
        {
          "title": faker.person.jobTitle(),
          "link": "https://www.forbes.com/companies/apple/",
          "snippet": "Apple Inc. engages in the design, manufacture, and sale of smartphones, personal computers, tablets, wearables and accessories, and other variety of related ...",
          "position": 7
        }
      ],
      "peopleAlsoAsk": [
        {
          "question": "What is Apple Inc.?",
          "snippet": "In 2007, Apple Computer changed its name to Apple Inc., reflecting a shift from creating primarily personal computing devices to providing a full line of consumer electronics, such as the iPad and iPhone, as well as content marketplaces to support these devices.",
          "title": faker.person.jobTitle(),
          "link": "https://www.ebsco.com/research-starters/computer-science/apple-inc"
        },
        {
          "question": "What if I invested $1000 in Apple in 1997?",
          "snippet": "If one had bought $1,000 in Apple stock when Jobs returned in February 1997 and held on until today, that position would be worth around $1.8 million.",
          "title": faker.person.jobTitle(),
          "link": "https://www.aol.com/youd-invested-1-000-apple-223207934.html"
        },
        {
          "question": "Is Apple called Apple or Apple Inc.?",
          "snippet": "Founded in 1976 as Apple Computer Company by Steve Jobs, Steve Wozniak and Ronald Wayne, the company was incorporated by Jobs and Wozniak as Apple Computer, Inc. the following year. It was renamed to its current name in 2007 as the company had expanded its focus from computers to consumer electronics.",
          "title": faker.person.jobTitle(),
          "link": "https://en.wikipedia.org/wiki/Apple_Inc."
        }
      ],
      "relatedSearches": [
        {
          "query": "Apple Inc address"
        },
        {
          "query": "Apple Inc USA"
        },
        {
          "query": "Apple Inc website"
        },
        {
          "query": "Apple Inc stock"
        },
        {
          "query": "Apple Inc investor relations"
        },
        {
          "query": "Apple Inc careers"
        },
        {
          "query": "Apple Inc logo"
        },
        {
          "query": "Apple inc LinkedIn"
        }
      ],
      "credits": 1
    };
  }
};
