// Auto-generated by zen-mock-data script
module.exports = {
  path: 'maps',
  method: 'POST',
  generate: (faker, requestBody) => {
    return {
      "searchParameters": {
        "q": "B2B SaaS Companies near Me",
        "type": "maps",
        "num": 10,
        "page": 1,
        "ll": "43.2635939,-122.4255654",
        "engine": "google"
      },
      "ll": "@39.7608488,-75.5657925,12z",
      "places": [
        {
          "position": 1,
          "title": faker.person.jobTitle(),
          "address": faker.location.streetAddress(),
          "latitude": 39.723326799999995,
          "longitude": -75.6570387,
          "rating": 5,
          "ratingCount": 2,
          "type": "Software company",
          "types": [
            "Software company"
          ],
          "website": faker.internet.url(),
          "phoneNumber": faker.phone.number({ style: 'international' }),
          "openingHours": {
            "Thursday": "Open 24 hours",
            "Friday": "Open 24 hours",
            "Saturday": "Open 24 hours",
            "Sunday": "Closed",
            "Monday": "Open 24 hours",
            "Tuesday": "Open 24 hours",
            "Wednesday": "Open 24 hours"
          },
          "thumbnailUrl": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweoZuHElj6gWgvGO-6nk8a6k-a9KFxqLJ4QKxt9DSgTFdUqZbvswbbSQe1sOSEwVRl4uyrHPoYJvPMGCc5hYo3f9BQhwDIiuwCqDmHPQDa_wtRKMqdlOblNVwbkYKQM7GMgi-uYH3w",
          "cid": "10767982426399615889",
          "fid": "0x89c7018663394ad1:0x956f8ef73132ab91",
          "placeId": "ChIJ0Uo5Y4YBx4kRkasyMfeOb5U"
        },
        {
          "position": 2,
          "title": faker.person.jobTitle(),
          "address": faker.location.streetAddress(),
          "latitude": 39.7317526,
          "longitude": -75.57838679999999,
          "rating": 5,
          "ratingCount": 6,
          "type": "Software company",
          "types": [
            "Software company",
            "Business to business service",
            "Computer support and services",
            "Design agency",
            "E-commerce service",
            "Internet marketing service",
            "Website designer"
          ],
          "website": faker.internet.url(),
          "phoneNumber": faker.phone.number({ style: 'international' }),
          "openingHours": {
            "Thursday": "Open 24 hours",
            "Friday": "Open 24 hours",
            "Saturday": "Closed",
            "Sunday": "Closed",
            "Monday": "Open 24 hours",
            "Tuesday": "Open 24 hours",
            "Wednesday": "Open 24 hours"
          },
          "thumbnailUrl": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepK98U5z6MAEWENjcWtj3izi-_9kL2pam0n4AIQTuH8EWpYIs41lfqqe5l-HCVfDdNRDG-zrUSK0SAOkZJVeSa--eyhN5B7CseRjCtB9Mj5yQoHm5G3PEK42fEcdTxwImUZHRqe5w",
          "cid": "168331039803505617",
          "fid": "0x89c6fd335b582bad:0x25608305828fbd1",
          "placeId": "ChIJrStYWzP9xokR0fsoWDAIVgI"
        },
        {
          "position": 3,
          "title": faker.person.jobTitle(),
          "address": faker.location.streetAddress(),
          "latitude": 39.7809041,
          "longitude": -75.59926639999999,
          "rating": 4.7,
          "ratingCount": 77,
          "type": "Software company",
          "types": [
            "Software company"
          ],
          "website": faker.internet.url(),
          "openingHours": {
            "Thursday": "Open 24 hours",
            "Friday": "Open 24 hours",
            "Saturday": "Open 24 hours",
            "Sunday": "Open 24 hours",
            "Monday": "Open 24 hours",
            "Tuesday": "Open 24 hours",
            "Wednesday": "Open 24 hours"
          },
          "thumbnailUrl": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqFJxRKScRMbmRsqL44nGVR9hMtRUUoBQ1feqeAd_Tv5bI1uO4lw01h2x2LkTLw2c4m7glnvJGBGBKwu7FLi313_QriBMzmQGS-iihZoeUibUyQtjzSoMG6y6vwwdpzWX4i3uTZbQ",
          "cid": "11867509035463547744",
          "fid": "0x89c25b97b0615555:0xa4b1dc974b8b1b60",
          "placeId": "ChIJVVVhsJdbwokRYBuLS5fcsaQ"
        },
        {
          "position": 4,
          "title": faker.person.jobTitle(),
          "address": faker.location.streetAddress(),
          "latitude": 39.746619599999995,
          "longitude": -75.5490043,
          "rating": 3.2,
          "ratingCount": 17,
          "type": "Software company",
          "types": [
            "Software company"
          ],
          "website": faker.internet.url(),
          "phoneNumber": faker.phone.number({ style: 'international' }),
          "openingHours": {
            "Thursday": "Open 24 hours",
            "Friday": "Open 24 hours",
            "Saturday": "Closed",
            "Sunday": "Closed",
            "Monday": "Open 24 hours",
            "Tuesday": "Open 24 hours",
            "Wednesday": "Open 24 hours"
          },
          "thumbnailUrl": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerK-PfKKWP8n4nYW12__8Vfid2g-jdwjUjPFdP1jHzR36-edQPz-I7OmqsQTIq2zBG6MJjvc_ZthCK9TBq2bKeTH3WbgRbZsb9HJ7pmk_0veB9Z-y_FEsSAl55IIHyguZYoRhvX",
          "cid": "10753418765974839446",
          "fid": "0x89c6fd72c5a3a591:0x953bd164c2f32096",
          "placeId": "ChIJkaWjxXL9xokRliDzwmTRO5U"
        },
        {
          "position": 5,
          "title": faker.person.jobTitle(),
          "address": faker.location.streetAddress(),
          "latitude": 39.790465499999996,
          "longitude": -75.4745464,
          "type": "Software company",
          "types": [
            "Software company",
            "Business management consultant",
            "Payroll service"
          ],
          "website": faker.internet.url(),
          "phoneNumber": faker.phone.number({ style: 'international' }),
          "openingHours": {
            "Thursday": "Open 24 hours",
            "Friday": "Open 24 hours",
            "Saturday": "Open 24 hours",
            "Sunday": "Open 24 hours",
            "Monday": "Open 24 hours",
            "Tuesday": "Open 24 hours",
            "Wednesday": "Open 24 hours"
          },
          "thumbnailUrl": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqbSinE0QrLCTUCIAE8PZclPpybJuBErOeViQUMXO6lXpK6XTxCa_pJnjPnpWrk-rjGYT3Cf8UEXoVDF8ckclmtZg7iUL7267qFb6LCVDZm2dbgRddkT_8nJe1QWvdesy1QIGso1w",
          "cid": "11595065745458293933",
          "fid": "0x89c6e312aacd3051:0xa0e9f2dcb9576cad",
          "placeId": "ChIJUTDNqhLjxokRrWxXudzy6aA"
        },
        {
          "position": 6,
          "title": faker.person.jobTitle(),
          "address": faker.location.streetAddress(),
          "latitude": 39.7809193,
          "longitude": -75.5993257,
          "type": "Software company",
          "types": [
            "Software company"
          ],
          "website": faker.internet.url(),
          "openingHours": {
            "Thursday": "Open 24 hours",
            "Friday": "Open 24 hours",
            "Saturday": "Open 24 hours",
            "Sunday": "Closed",
            "Monday": "Open 24 hours",
            "Tuesday": "Open 24 hours",
            "Wednesday": "Open 24 hours"
          },
          "thumbnailUrl": "https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=5PL0yZPC5M4N97kpi2UH5A&cb_client=search.gws-prod.gps&w=80&h=92&yaw=67.9659&pitch=0&thumbfov=100",
          "cid": "1168962470899814708",
          "fid": "0x89c6fdf4e8234649:0x1038fd2c81bf1134",
          "placeId": "ChIJSUYj6PT9xokRNBG_gSz9OBA"
        },
        {
          "position": 7,
          "title": faker.person.jobTitle(),
          "address": faker.location.streetAddress(),
          "latitude": 39.798370899999995,
          "longitude": -75.4971545,
          "rating": 4.3,
          "ratingCount": 16,
          "type": "Software company",
          "types": [
            "Software company"
          ],
          "website": faker.internet.url(),
          "phoneNumber": faker.phone.number({ style: 'international' }),
          "thumbnailUrl": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweostMe7NxZWPeh0z2CMWgRdYTOhEamMWqnistVeHWigjm4_iuD1JZXzxXWqPi0R1l1fK8eZcRB7oySuRnvskdaQHJAf2DBMoxFL2fRuGpVQWl3WX5Dyg_yJKI8khamEfnTZEEM5",
          "cid": "16678616855031173425",
          "fid": "0x8085819a66cdd879:0xe77659a99cf9d131",
          "placeId": "ChIJedjNZpqBhYARMdH5nKlZduc"
        }
      ],
      "credits": 3
    };
  }
};
