const fs = require('fs');
const path = require('path');

const inputDir = path.join(__dirname, '../input-data');
const providersDir = path.join(__dirname, '../providers');

const HEURISTICS = {
  first_name: "faker.person.firstName()",
  firstname: "faker.person.firstName()",
  last_name: "faker.person.lastName()",
  lastname: "faker.person.lastName()",
  name: "faker.person.fullName()",
  full_name: "faker.person.fullName()",
  fullname: "faker.person.fullName()",
  email: "faker.internet.email()",
  work_email: "faker.internet.email()",
  workemail: "faker.internet.email()",
  contact_email: "faker.internet.email()",
  contactemail: "faker.internet.email()",
  company: "faker.company.name()",
  company_name: "faker.company.name()",
  companyname: "faker.company.name()",
  organization: "faker.company.name()",
  organization_name: "faker.company.name()",
  organizationname: "faker.company.name()",
  title: "faker.person.jobTitle()",
  job_title: "faker.person.jobTitle()",
  jobtitle: "faker.person.jobTitle()",
  phone: "faker.phone.number()",
  phone_number: "faker.phone.number()",
  phonenumber: "faker.phone.number()",
  website: "faker.internet.url()",
  domain: "faker.internet.domainName()",
  city: "faker.location.city()",
  state: "faker.location.state()",
  country: "faker.location.country()",
  zip: "faker.location.zipCode()",
  address: "faker.location.streetAddress()",
  id: "faker.string.uuid()",
  uuid: "faker.string.uuid()",
  created_at: "faker.date.past()",
  createdat: "faker.date.past()",
  updated_at: "faker.date.recent()",
  updatedat: "faker.date.recent()"
};

// Traverses the response object and applies Faker logic
function processResponse(data) {
  if (Array.isArray(data)) {
    return data.map(item => processResponse(item));
  } else if (data !== null && typeof data === 'object') {
    const newObj = {};
    for (const [key, value] of Object.entries(data)) {
      if (typeof value === 'object') {
        newObj[key] = processResponse(value);
      } else if (typeof value === 'string') {
        // 1. Manual Override check: "{{company.name}}" -> "faker.company.name()"
        const overrideMatch = value.match(/^\{\{(.+?)\}\}$/);
        if (overrideMatch) {
          newObj[key] = `__FAKER_MAGIC_faker.${overrideMatch[1]}()__FAKER_MAGIC__`;
        } 
        // 2. Heuristic Guessing
        else if (HEURISTICS[key.toLowerCase()]) {
          newObj[key] = `__FAKER_MAGIC_${HEURISTICS[key.toLowerCase()]}__FAKER_MAGIC__`;
        } 
        // 3. Fallback to original value
        else {
          newObj[key] = value;
        }
      } else {
        newObj[key] = value;
      }
    }
    return newObj;
  }
  return data;
}

function run() {
  if (!fs.existsSync(inputDir)) {
    console.error(`❌ Input directory not found: ${inputDir}`);
    return;
  }

  const files = fs.readdirSync(inputDir).filter(f => f.endsWith('.json') && !f.startsWith('DONE-'));

  if (files.length === 0) {
    console.log(`ℹ️ No new JSON files to process in input-data/.`);
    return;
  }

  files.forEach(file => {
    const inputPath = path.join(inputDir, file);
    const donePath = path.join(inputDir, `DONE-${file}`);
    
    try {
      console.log(`⏳ Processing ${file}...`);
      const rawData = fs.readFileSync(inputPath, 'utf8');
      const json = JSON.parse(rawData);

      if (!json._meta || (!json.response && json.response !== null)) {
        throw new Error('Missing `_meta` or `response` in JSON structure.');
      }

      const { provider, path: routePath, method } = json._meta;
      
      if (!provider || !routePath || !method) {
        throw new Error('Missing `provider`, `path`, or `method` in `_meta`.');
      }

      // Process response with hybrid heuristics
      const processedResponse = processResponse(json.response);

      // Convert to string and unquote the magic faker injections
      let stringified = JSON.stringify(processedResponse, null, 2);
      stringified = stringified.replace(/"__FAKER_MAGIC_(.*?)__FAKER_MAGIC__"/g, '$1');

      // Create JS template
      const jsContent = `// Auto-generated by zen-mock-data script
module.exports = {
  path: '${routePath}',
  method: '${method.toUpperCase()}',
  generate: (faker, requestBody) => {
    return ${stringified};
  }
};
`;

      // Save to providers/ folder
      const targetProviderDir = path.join(providersDir, provider);
      if (!fs.existsSync(targetProviderDir)) {
          fs.mkdirSync(targetProviderDir, { recursive: true });
      }

      // Determine output file name
      let outFileName = file.replace('.json', '');
      if (outFileName.startsWith(`${provider}-`)) {
          outFileName = outFileName.replace(`${provider}-`, '');
      }
      
      const outFilePath = path.join(targetProviderDir, `${outFileName}.js`);
      
      fs.writeFileSync(outFilePath, jsContent, 'utf8');
      
      // Rename effectively completing it
      fs.renameSync(inputPath, donePath);
      
      console.log(`✅ Success! Generated provider at: providers/${provider}/${outFileName}.js`);

    } catch (e) {
      console.error(`❌ Failed to process ${file}:`, e.message);
    }
  });
}

run();
